services:
  redis:
    image: redis:7
    container_name: euamoia-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./euamoia_redis:/data

  postgres:
    image: postgres:16
    container_name: euamoia-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-euamoia}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    image: node:18
    container_name: euamoia-front
    working_dir: /app
    volumes:
      - ./euamoia_front:/app
    environment:
      - VITE_API_URL=http://localhost:3001
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - backend

  backend:
    image: node:18
    container_name: euamoia-back
    working_dir: /app
    volumes:
      - ./euamoia_back:/app
    command: sh -c "npm install --legacy-peer-deps && npm run start:dev"
    ports:
      - "3001:3001"
      - "4983:4983"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - REDIS_URL=redis://euamoia-redis:6379
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-key}
      - NODE_ENV=development
    depends_on:
      redis:
        condition: service_started

  drizzle-studio:
    image: node:18
    container_name: euamoia-drizzle-studio
    working_dir: /app
    volumes:
      - ./euamoia_back:/app
    command: sh -c "npm install --legacy-peer-deps && npx drizzle-kit studio --host 0.0.0.0 --port 4000"
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy

  # Alternative: Local-only Drizzle Studio (if cloud version doesn't work)
  drizzle-local:
    image: node:18
    container_name: euamoia-drizzle-local
    working_dir: /app
    volumes:
      - ./euamoia_back:/app
    command: sh -c "npm install --legacy-peer-deps && npx @drizzle-team/studio --port 4001 --host 0.0.0.0"
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - local-studio

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: euamoia-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    name: euamoia-net 

volumes:
  postgres_data: 